# Generated by Django 4.1.7 on 2023-03-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.TextField(max_length=50)),
                ('rut', models.TextField(max_length=9)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.TextField(max_length=9)),
                ('sexo', models.TextField(max_length=12)),
                ('mail', models.TextField(max_length=100)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
