# Generated by Django 4.1.7 on 2023-03-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_cliente_fecha_ingreso_remove_cliente_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecto',
            name='cliente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.cliente'),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='estado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.estado'),
        ),
        migrations.AlterField(
            model_name='prospecto',
            name='etapa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.etapa'),
        ),
    ]
