### listado de todos los clientes
GET http://localhost:8000/app/clientes/

### Buscar un cliente cambiando el ultimo número
GET http://localhost:8000/app/clientes/2 

### Crear nuevo cliente
POST http://localhost:8000/app/clientes/
Content-Type: application/json

{
  "nombre_empresa": "Luis",
  "rut": "205077988",
  "direccion": "calle 229",
  "telefono": "922277789",
  "sexo": "femenino",
  "mail": "luis.14@gmail.com"
}

### Actualizar datos de un cliente - cambiar último número en la url
PUT http://localhost:8000/app/clientes/1
Content-Type: application/json

{
  "nombre_empresa": "Sofia",
  "rut": "113337923",
  "direccion": "calle 7889",
  "telefono": "123456789",
  "sexo": "femenino",
  "mail": "Ana.sofia@gmail.com"
}